name: Publish the Excel Frontend Application as Docker Image to GHCR

on:
  push:
    branches:
      - production

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run:
          docker login -u AdelQraft -p ${{secrets.GH_PACKAGE_PAT}} ghcr.io

      - name: Build the Excel Frontend Application
        run:
          cp ./.env.prod.template ./.env.prod &&
          npm i &&
          npm run docker-build

      - name: Push the Docker Image to GHCR
        run:
          docker push $(docker images | grep 'ghcr.io/adelqraft/grocery_scraper_frontend_excel' | awk '{print $1 ":" $2}')
