name: Publish the Excel Frontend Application to GitHub Pages

on:
  push:
    branches:
      - production

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # no backend service available at the moment, so only provide a local one
      - name: Build the Excel Frontend Application
        run:
          cp ./.env.dev.template ./.env.dev &&
          npm i &&
          ls -la --color=auto &&
          mkdir gh_pages &&
          FRONTEND_URL="https://adelqraft.github.io/grocery_scraper_frontend_excel/add-in" BACKEND_URL="https://httpbin.org/status/503" ENVIRONMENT_DEFINITION_URL="/grocery_scraper_frontend_excel/add-in/env_def.json" npm run build:dev &&
          ls -la --color=auto &&
          cat .env.dev &&
          mv dist_dev gh_pages/add-in &&
          FRONTEND_URL="https://adelqraft.github.io/grocery_scraper_frontend_excel/add-in-local" BACKEND_URL="http://localhost:8084" ENVIRONMENT_DEFINITION_URL="/grocery_scraper_frontend_excel/add-in-local/env_def.json" npm run build:dev &&
          mv dist_dev gh_pages/add-in-local

      - name: Push the website to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: gh_pages
          branch: production-deployment
          token: ${{secrets.GH_REPOS_PAT}}
